# Generated by Django 6.0.5 on 2026-05-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cpf", models.CharField(max_length=14)),
                ("cnpj", models.CharField(max_length=18)),
                ("cep", models.CharField(max_length=9)),
                ("endereco", models.CharField(max_length=200)),
                ("numero", models.IntegerField()),
                ("bairro", models.CharField(max_length=100)),
                ("cidade", models.CharField(max_length=100)),
                ("uf", models.CharField(max_length=2)),
                ("celular", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
