# Generated by Django 6.0.5 on 2026-05-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0003_alter_cliente_cnpj_alter_cliente_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="cnpj",
            field=models.CharField(default="", max_length=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cpf",
            field=models.CharField(default="", max_length=14),
            preserve_default=False,
        ),
    ]
